version: '3.8'

services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: reclaim_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart_reimburse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:z
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d smart_reimburse" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      # dockerfile: Dockerfile
      dockerfile: uv.Dockerfile
    container_name: reclaim_backend
    restart: unless-stopped
    volumes:
      - ./backend:/app:z
      - /app/.venv
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - DATABASE_URL=postgresql://admin:password@db:5432/smart_reimburse
    depends_on:
      db:
        condition: service_healthy
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    command: bash -c "python -c 'from core.database import init_db; init_db()' && alembic stamp head && python seed_demo_employees.py && python seed_mock_policy.py && python seed_mock_data.py && exec uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      # test: [ "CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" ]
      test: [ "CMD", "/app/.venv/bin/python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reclaim_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
      - next_cache:/app/.next
    ports:
      - "3000:3000"
    user: root
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - INTERNAL_API_URL=http://backend:8000
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_healthy
    command: npm run dev
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  next_cache:
