version: '3.8'

services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: reclaim_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:z
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d smart_reimburse" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      # dockerfile: Dockerfile
      dockerfile: uv.Dockerfile
    container_name: reclaim_backend
    restart: unless-stopped
    volumes:
      - ./backend:/app:z
      - /app/.venv
    expose:
      - "8000"
    environment:
      # - WATCHFILES_FORCE_POLLING=true
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_BASE_URL=${LLM_BASE_URL}
      - CHAT_MODEL=${CHAT_MODEL}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_BASE_URL=${OPENROUTER_BASE_URL}
      - VISION_MODEL=${VISION_MODEL}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "python -c 'from core.database import init_db; init_db()' && alembic stamp head && exec uvicorn main:app --host 0.0.0.0 --port 8000"
    # command: bash -c "python -c 'from core.database import init_db; init_db()' && alembic stamp head && python seed_demo_employees.py && python seed_mock_policy.py && python seed_mock_data.py && exec uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      # test: [ "CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" ]
      test: [ "CMD", "/app/.venv/bin/python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reclaim_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
      - next_cache:/app/.next
    expose:
      - "3000"
    user: root
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - INTERNAL_API_URL=${INTERNAL_API_URL}
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      backend:
        condition: service_healthy
    command: npm run start
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3001/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  next_cache:
