"""add payouts notifications and banking fields

Revision ID: cb6ce2252fcc
Revises: 62328b82ed1f
Create Date: 2026-05-01 19:19:24.741272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6ce2252fcc'
down_revision: Union[str, None] = '62328b82ed1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['employees.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('payouts',
    sa.Column('payout_id', sa.Uuid(), nullable=False),
    sa.Column('reim_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('xendit_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('channel_code', sa.String(), nullable=False),
    sa.Column('failure_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reim_id'], ['reimbursements.reim_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['employees.user_id'], ),
    sa.PrimaryKeyConstraint('payout_id')
    )
    op.create_index(op.f('ix_payouts_reim_id'), 'payouts', ['reim_id'], unique=False)
    op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
    op.create_index(op.f('ix_payouts_user_id'), 'payouts', ['user_id'], unique=False)
    op.add_column('employees', sa.Column('bank_code', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('bank_account_number', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('bank_account_holder_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'bank_account_holder_name')
    op.drop_column('employees', 'bank_account_number')
    op.drop_column('employees', 'bank_code')
    op.drop_index(op.f('ix_payouts_user_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_reim_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
