// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/employee/claims" | "/employee/dashboard" | "/employee/history" | "/employee/settings" | "/employee/submit" | "/employee/support" | "/hr/dashboard" | "/hr/history" | "/hr/policy" | "/hr/review/[id]" | "/hr/settings" | "/hr/support" | "/hr/view/[id]" | "/login"
type PageRoutes = never
type LayoutRoutes = "/" | "/employee" | "/hr"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/employee": {}
  "/employee/claims": {}
  "/employee/dashboard": {}
  "/employee/history": {}
  "/employee/settings": {}
  "/employee/submit": {}
  "/employee/support": {}
  "/hr": {}
  "/hr/dashboard": {}
  "/hr/history": {}
  "/hr/policy": {}
  "/hr/review/[id]": { "id": string; }
  "/hr/settings": {}
  "/hr/support": {}
  "/hr/view/[id]": { "id": string; }
  "/login": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/employee": never
  "/hr": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
