// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../app/employee/claims/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employee/claims">> = Specific
  const handler = {} as typeof import("../../../app/employee/claims/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employee/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employee/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/employee/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employee/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employee/history">> = Specific
  const handler = {} as typeof import("../../../app/employee/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employee/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employee/settings">> = Specific
  const handler = {} as typeof import("../../../app/employee/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employee/submit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employee/submit">> = Specific
  const handler = {} as typeof import("../../../app/employee/submit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employee/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employee/support">> = Specific
  const handler = {} as typeof import("../../../app/employee/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/hr/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/hr/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/hr/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/history">> = Specific
  const handler = {} as typeof import("../../../app/hr/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/hr/policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/policy">> = Specific
  const handler = {} as typeof import("../../../app/hr/policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/hr/review/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/review/[id]">> = Specific
  const handler = {} as typeof import("../../../app/hr/review/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/hr/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/settings">> = Specific
  const handler = {} as typeof import("../../../app/hr/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/hr/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/support">> = Specific
  const handler = {} as typeof import("../../../app/hr/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/hr/view/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/view/[id]">> = Specific
  const handler = {} as typeof import("../../../app/hr/view/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../app/employee/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/employee">> = Specific
  const handler = {} as typeof import("../../../app/employee/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/hr/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/hr">> = Specific
  const handler = {} as typeof import("../../../app/hr/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
